### ISSUE TITLE
missing argument 'consumerkey'

### ISSUE THREAD

**Issue by jeangui** [antoinerousseau/flickr2google#2]
Hello Antoine

I am getting a error even if I have filled the env file with correct key & secret for Google Photos and Flickr API.

`2020-01-03 20:36:16 Error: Missing required argument "consumerKey"
    at new OAuth (C:\Users\XA73616\Documents\GitHub\flickr2google\node_modules\flickr-sdk\services\oauth.js:41:9)
    at module.exports (C:\Users\XA73616\Documents\GitHub\flickr2google\flickr.js:9:23)`

What am I doing wrong ?

node version : v12.14.0

Thanks in advance for your help

Best

**Comment by OliPetry** [comment]
I have the exact same issue. Same version of node, but on MacOS Catalina.

**Comment by antoinerousseau** [comment]
I could only reproduce the issue by removing the Flickr constants from the `.env` file. Are you sure you created that file and added both `FLICKR_APP_KEY` and `FLICKR_APP_SECRET` constants in it?

I just pushed commit 7630494 on `master`, get it and try again, it should tell you if the constants are missing.
